//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectosMUNIVALPO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNI_usuario
    {
        public string id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string contrasena { get; set; }
    }
}
