//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectosMUNIVALPO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNI_archivo
    {
        public int id_archivo { get; set; }
        public string archivo { get; set; }
        public int id_proyecto { get; set; }
    
        public virtual MUNI_proyecto MUNI_proyecto { get; set; }
    }
}
