//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectosMUNIVALPO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNI_responsable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUNI_responsable()
        {
            this.MUNI_proyecto = new HashSet<MUNI_proyecto>();
        }
    
        public int id_responsable { get; set; }
        public string correo { get; set; }
        public string descipcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUNI_proyecto> MUNI_proyecto { get; set; }
    }
}
