//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectosMUNIVALPO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNI_proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUNI_proyecto()
        {
            this.MUNI_archivo = new HashSet<MUNI_archivo>();
        }
    
        public int id_proyecto { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public string bajada { get; set; }
        public string descripcion { get; set; }
        public int id_tipoProyecto { get; set; }
        public int id_responsable { get; set; }
        public int id_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUNI_archivo> MUNI_archivo { get; set; }
        public virtual MUNI_estado MUNI_estado { get; set; }
        public virtual MUNI_responsable MUNI_responsable { get; set; }
        public virtual MUNI_tipo_proyecto MUNI_tipo_proyecto { get; set; }
    }
}
